[MOSIP-29979] added mounting path during docker run time
mosip/data-archive pull request #11
Opened 2023-12-20 13:06 UTC by bhumi46

2023-12-21 08:11 UTC, syedsalman3753 requested changes
@bhumi46 

I believe this was decide that variable `need_archival` in json will be changed to `operation_type`

operation_type:
* delete   ( no archive , on delete entries from table )
* archieve_delete ( archive + delete entries )
* archieve_nodelete ( archive + no delete entries )

2023-12-27 09:21 UTC, syedsalman3753 approved these changes

2023-12-27 11:00 UTC, ckm007 reviewed
Can we add a Readme here listing all the values for required keys in values.yaml

2023-12-28 10:43 UTC, ckm007 approved these changes

2023-12-28 10:43 UTC, merged